version: '3.1'

# For spark-common settings
x-spark-common:
  &spark-common
  image: local/spark:3.5.1
  build:
      context: ./spark
      dockerfile: Dockerfile
  profiles: ["spark"]
  networks:
      - delta-net

services:

  spark-master:
    <<: *spark-common
    container_name: spark-master
    ports:
      # - 4040:4040
      - 7077:7077
      - 8080:8080
      # - 18080:18080 
    command: sh entrypoint.sh master

  spark-worker-1:
    <<: *spark-common
    container_name: spark-worker-1
    ports:
      # - "8081-8085:8081"
      - 8081:8081
    command: sh entrypoint.sh worker
    depends_on:
      - spark-master
    
  
  spark-worker-2:
    <<: *spark-common
    container_name: spark-worker-2
    ports:
      # - "8081-8085:8081"
      - 8082:8081
    command: sh entrypoint.sh worker
    depends_on:
      - spark-master
  
  spark-history:
    <<: *spark-common
    container_name: spark-history
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 18080:18080
    command: sh entrypoint.sh history
    depends_on:
      - spark-master
    

